# This uses newer and faster docker based build system
sudo: false

language: php

php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  # Sanity composer check
  - composer validate --strict

script:
  # Sanity php syntax check
  - php -l src/Dropin.php

  # Install phpunit etc
  - composer install --prefer-dist

  # Run the real tests finally
  - composer test
