# This uses newer and faster docker based build system
sudo: false

language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update

  # We use the same repo straight from github because it required lesser amount of hacks
  # Here we force the same current git commit id for composer
  - sed -i -e "s|%%TRAVIS_COMMIT%%|$TRAVIS_COMMIT|g" tests/move/composer.json
  - sed -i -e "s|%%TRAVIS_COMMIT%%|$TRAVIS_COMMIT|g" tests/copy/composer.json

  # Install test run into tests/ folder using tests/composer.json
  - composer install --working-dir=./tests/move/
  - composer install --working-dir=./tests/copy/

script:
  # Sanity php syntax check
  - php -d error_reporting=32767 -l src/Dropin.php

  # Sanity composer check
  - composer validate composer.json

  # Install phpunit etc
  - composer install

  # Run the real tests finally
  - composer test
