language: php

php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'
  - nightly

jobs:
  allow_failures:
    - php: nightly

before_install:
  - git fetch --unshallow
  # Sanity composer check
  - composer validate --strict

install:
  # Install phpunit etc
  - composer update --prefer-dist

script:
  # Sanity php syntax check
  - php -l src/Dropin.php

  # Run the real tests finally
  - composer run-script -v test
